@Api_HostAddress = http://127.0.0.1:55077

POST {{Api_HostAddress}}/api/students
Content-Type: application/json

{
  "username": "Søren",
  "password": "hemmelig1",
  "parentEmail": "foraelder@example.com",
  "grade": 7,
  "interestIds": []
}